# Generated by Django 5.1.6 on 2025-04-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_tagpost_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
    ]
