# Generated by Django 5.2.1 on 2025-06-30 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_author_alter_post_cat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-time_create'], name='post_post_time_cr_623b2b_idx'),
        ),
    ]
